name: for_u_win
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  qr_flutter: ^4.0.0
  loading_animation_widget: ^1.3.0
  carousel_slider: ^4.2.1
  shared_preferences: ^2.5.3
  mobile_scanner: ^7.0.0
  provider: ^6.1.5
  pdf: ^3.10.4
  printing: ^5.14.2
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  flutter_pdfview: ^1.4.0+1
  permission_handler: ^11.0.1
  http: ^1.4.0
  photo_manager: ^3.2.0 
  intl: ^0.20.2
  sunmi_printer_plus: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/