name: for_u_win
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  bluetooth_print_plus: ^2.4.6
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  google_fonts: ^6.2.1
  http: ^1.4.0
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  mobile_scanner: ^7.0.0
  open_file: ^3.5.10
  path_provider: ^2.1.1
  pdf: ^3.10.4
  timezone: ^0.9.2
  permission_handler: ^11.0.1
  printing: ^5.14.2
  provider: ^6.1.5
  qr_flutter: ^4.0.0
  # esc_pos_utils_plus: ^2.0.4
  # flutter_bluetooth_printer: ^2.19.0
  # flutter_pdfview: ^1.4.0+1
  # share_plus: ^7.2.1
  shared_preferences: ^2.5.3
  sunmi_printer_plus: ^4.1.0
  kiosk_mode: ^0.7.0
  # url_launcher: ^6.2.2
  # device_policy_controller: ^0.0.3+1
  # qr_code_scanner_plus: ^2.0.0
  # disable_battery_optimization: ^1.1.1
  # ignore_battery_optimizations:
  # battery_optimization_helper: ^0.0.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/